# https://zero-to-jupyterhub.readthedocs.io/en/latest/reference/reference.html
proxy:
  secretToken: "57856fad13702360592b9a1a97d1924c406f465390615934957d05422bc7d24a"
  # it's fine to keep the secret token public, since it's only for testing anyway
  # same reason why we're disabling https
  https:
    enabled: false
singleuser:
  memory:
    limit: 512M
    guarantee: 128M
auth:
  dummy:
    # change every time you test and expose the server to the public
    password: '7ae5f2913ace99ea5150bc44ca07b9ca'
  admin:
    users:
      - rkevin
hub:
  extraConfig:
    ngshare.py: |
      c.JupyterHub.services.append({
        'name': 'ngshare',
        'url': 'http://ngshare:8080',
        'api_token': '311d1d3e5d8660ae3f4059c36da312d4'})
singleuser:
  image:
    name: singleuser-testing
    tag: 0.0.1
    imagePullPolicy: Always
debug:
  enabled: true
