language: python
python:
- 3.6
- 3.7
- 3.8
- nightly
jobs:
  allow_failures:
  - python: nightly
addons:
  apt:
    packages:
    - python3-pip
services:
- docker
cache: pip
before_install:
- python3 -m pip install setuptools wheel
- curl -L https://git.io/get_helm.sh | bash && sudo mv `which helm` `which helm`2
- curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
install:
- python3 -m pip install .
before_script:
- python3 -m pip install -r testing_reqs.txt
script:
- python3 -m black -S -l 80 --check .
- helm2 lint --strict helmchart/ngshare
- helm lint --strict helmchart/ngshare
- python3 -m pytest ./ngshare/ --cov=./ngshare/
after_success:
- codecov
- |-
  test ${TRAVIS_PYTHON_VERSION} = 3.8 &&
  test -n "${DOCKER_PASSWORD}" &&
  echo '{"mtu": 1460}' | sudo dd of=/etc/docker/daemon.json &&
  sudo systemctl restart docker &&
  docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" &&
  openssl aes-256-cbc -K $encrypted_defe1004a0ce_key -iv $encrypted_defe1004a0ce_iv -in helmchart/ssh_key.enc -out /tmp/ssh_key -d &&
  chmod 400 /tmp/ssh_key &&
  python3 -m pip install chartpress docker==4.2.1 &&
  GIT_SSH_COMMAND="ssh -i /tmp/ssh_key" chartpress --push --publish-chart --long &&
  test -n "${TRAVIS_TAG}" &&
  GIT_SSH_COMMAND="ssh -i /tmp/ssh_key" chartpress --push --publish-chart --tag "${TRAVIS_TAG}"
deploy:
  provider: pypi
  user: __token__
  password:
    secure: CnzfP5f78cuucJXf9Abgu2c9CC88/e/bo/b4lFGlcqZrjay5w0xG0arhGdIDWb8LtxmaX74l5Pm+QZi63uP+h5qUJiBh6pux1uhoyvtg3FMlpbHedqpPHYOYgqATeJ/UXeCTwFU37XZJQEJYB1YriwATYgdhpb0qbe105dVsBzhVuz+JNqyLXXPdaBXYlRYzr+77yHonh2Rq1tkzhGS3WrKByQT6y+PD+Eff0ADg390myXI9gpj1EMfc/gtfKjFWQFzY1E3stmt927BbMU/lPE+Ftz6JkwbnB0QK4u49vpdCZqBqJbdai9oS7hpa8ViZnY11w7fwZKCZHQ9uFRXiPyZAhMpv7mtv62ugoQTMfoMru19DuHAktd9RJ3cLKWfXI7ViJ1d1ZLIshYpB2wIRcXbcB6/iZ3HjhauL5Ez0hs0rTIcMQZda5OTQZqfh7cg81S/TJcu9nxAAsho71YLgxt0p9NdVUFc//DIBwW2Cv4oDo1HX8LsCDx9sG8zc0KIhz4gpAh2nQfi1JOvEPQ4X7eRHJGtFjWGzcmdIHnnVRyOsXfaNAROcAMyIpJEoCsM8nguARhJCJ9/Ga4BlsWSdxqUPNKN35Fz0Jb8cICiyKjD8Opvz1dknYVi0abzDJqLi0pZUkzSt69j9vtcKkrq1UtfzFkMk/ypKmrWA6oi/8HU=
  on:
    branch: stable
    python: '3.8'
env:
  global:
  - secure: N9yU8HBDfWAxUwU9NGBnq7eCee255WrCDl7h1zFUg5gz5XuSDxQaHkMgmv3qhuyDoaLkoBaA4HhybqGIlD3B06BfU9jx+iHy28NF6JI5v5CS5X/bsFGaxsl3f7mTw6cm6VP4SH8NCcPSW4MDVUq7ijdw95PUi3q9yrj3WDl36xGNbdcmhw77NBvaUROAMkeOUDpHW9VkvTJ8paYlVpA2U4LasAsa/3q6o2fYFyJ6V9BQSJ6c4T/SxkjHUIKpMJ4bpFqxElseIf4dAm0OyTV7dct4cMD/C6TfZeKo/vhyKSzXg5RAI+1l1GQWiNErqAe4bxb+5OPkgYvgt8vIpqKU0QMbfk6pih3r4Q7vs3PeT+MbGxIdiZ2q5cdQe2211ZBwOv3HohzasOUow7cIobLMGORMHPHg7JGdHje1MTVs9XmqDkq4916niYbqDTfdAZFAHBgU42zKJ5lsAulYZtqzv52keyaqa47orK6UP2HtjS/tiG4bT08FZ6BfJv5FCszi4si79EjdhRRo/ASsq4A6xgbqS9QV9YgeQyhmVbm9xHI4YaRXK6fWphuWaYWDnJd3U/TtH/Jpk198Gbq93Cr1rtrOP/7i/aJ2YQx9Z5o9odUfL/RsesNut3USUgfqSshsrosYE/uDBdV2yOafRt7Qrr1vydB5lnYQCCR7S2IGZd0=
  - secure: D41vAgHVParfr/C/YzTwtAe7VdtWadnOz2vC4u7j7F307ejKx7uVFUbCdWLB0WE0cHohnB069ezA4v2WEdGoOUfauPqVWY40pxYFvnr9hDhBOR8CgnaZVcOG/i1WMoqE7tEE020S4Oh9GLexI6j8evHhvFby0RR/IlzaI5YuEFRnbEJVZsh2kFRwlruM+znq3wmyXniXm6G5/B96vCo6C/VVKw4suKoviNodGFQrPqq0VwCqLlYzMvDlsyMFRtiNXXTK9ySwxf4dlEq/gv3qItACcGXV1Ey6vrm2nv49w1TLZdYfLyi2Dh6H9tn2WJwz7p4z+YS3kn3QO8pflJmuEOA5Gyq4RjfSCckfCAkwH1Zq5VuN9PyG0NKdOAtpivnAoNcPOHZeRFoJW1HCtStftNEeZbJ1hnQEaXl9nbF0F/T7K/r4tH8asPpPoUqFf93jp93CTilS5kwWDt+KAd67g2+gGzqVMl+FD4OtPYONMEfHYdz/rZh0JNZbFipcizUUxARJ5hSQ9WVgGIiPFxPMVOHuWul8yRDUWbqLKAhbYRu8w7otTqqM5dn10xzVqrYqFG4pOIRFm+axV3PPr9GI42xtpfWTwb2o2wyR87IpK42pJK6uGJbQHan1x5SHr0fT75v8N8cSZEnuvRtsW4OoXwq83TRsGycSRQnwDyPNEOA=
