apiVersion: v1
kind: Service
metadata:
  name: {{ include "ngshare.fullname" . }}
  labels:
    {{- include "ngshare.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.deployment.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "ngshare.selectorLabels" . | nindent 4 }}
